version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      - DATABASE_URI=mongodb://mongo:27017/mydatabase
  mongo:
    image: mongo
    ports:
      - "27017:27017"
